### ISSUE TITLE
请问项目要怎么运行呢？有无对应的报告或者文档？

### ISSUE THREAD

**Issue by deagle-z** [W-Java/CET6#1]

**Comment by W-Java** [comment]
首先打开服务端src/Server/Main，启动服务端。随后打开客户端与服务端进行连接，打开src/Client/Main_Window（或者直接打开项目目录下的jar文件）。客户端分别进行登录并进行匹配，随后进入游戏，当其中一方的成绩先为0的时候游戏结束。并且本地文件记录用户的答题情况。

**Comment by W-Java** [comment]
简单的文档可以在README.md文件中查看，报告可以在report.doc中查看

**Comment by W-Java** [comment]
还有不懂的可以随时问我

**Comment by hmxxgit** [comment]
> 还有不懂的可以随时问我

请问一直在加载中，显示空指针异常是什么原因呢？
